make: Subaru
generated_at: '2026-06-23T11:35:35.078375'
schema_version: '1.0'
token_map:
  6mt: TRANSMISSION
  auto: TRANSMISSION
  awd: DRIVETRAIN
  black: PACKAGE
  cvt: TRANSMISSION
  edition: PACKAGE
  fwd: DRIVETRAIN
  gt: TRIM
  hybrid: ENGINE_TYPE
  limited: TRIM
  manual: TRANSMISSION
  mt: TRANSMISSION
  package: PACKAGE
  pkg: PACKAGE
  sport: TRIM
  touring: TRIM
  wilderness: MODEL
  murasaki: MODEL
  technology: MODEL
  luxury: MODEL
  lr: MODEL
  raiu: MODEL
  sport-tech: MODEL
  forester: MODEL
  type: MODEL
  w/: MODEL
  ts: MODEL
  ascent: MODEL
  crosstrek: MODEL
  w/brown: MODEL
  brz: MODEL
  plug-in: MODEL
  outdoor: MODEL
  3.6r: MODEL
  uncharted: MODEL
  4-door: MODEL
  solterra: MODEL
  sti: MODEL
  impreza: MODEL
  w/black: MODEL
  e-boxer: MODEL
  outback: MODEL
  rs: MODEL
  2.4i: MODEL
  xt: MODEL
  kanrai: MODEL
  w/eyesight: MODEL
  w/rs: MODEL
  (mt): MODEL
  w/technology: MODEL
  legacy: MODEL
  w/luxury: MODEL
  spoiler: MODEL
  w/wing: MODEL
  leather: MODEL
  (6at): MODEL
  trailseeker: MODEL
  ra: MODEL
  5-door: MODEL
  8-passenger: MODEL
  7-passenger: MODEL
  onyx: MODEL
  '-': MODEL
  cladding: MODEL
  2.0xt: MODEL
  kaminari: MODEL
  premier: MODEL
  2.0i: MODEL
  convenience: MODEL
  wrx: MODEL
  w/lip: MODEL
  2.5i: MODEL
unclassified:
- 8-pass
- captains
- chairs
- spt
- with
