make: Honda
generated_at: '2026-06-23T11:35:35.045095'
schema_version: '1.0'
fuel_type_category: ENGINE_TYPE
token_map:
  4wd: DRIVETRAIN
  awd: DRIVETRAIN
  black: PACKAGE
  cvt: TRANSMISSION
  edition: PACKAGE
  ex: TRIM
  ex-l: TRIM
  hybrid: ENGINE_TYPE
  lx: TRIM
  mt: TRANSMISSION
  se: TRIM
  sport: TRIM
  touring: TRIM
  sport-b: MODEL
  lx-b: MODEL
  2wd: MODEL
  3d: MODEL
  trailsport: MODEL
  hybrid,: MODEL
  cr-v: MODEL
  type: MODEL
  prologue,touring: MODEL
  pilot: MODEL
  civic,: MODEL
  exl: MODEL
  si: MODEL
  4d: MODEL
  passport,: MODEL
  hatchback: MODEL
  blackout: MODEL
  hr-v,: MODEL
  ex-l,: MODEL
  accord,: MODEL
  odyssey: MODEL
  odyssey,: MODEL
  civic: MODEL
  hr-v: MODEL
  cr-v,: MODEL
  sport-l: MODEL
  ridgeline,: MODEL
  prelude: MODEL
  pilot,: MODEL
  sedan: MODEL
  ridgeline: MODEL
  r: MODEL
  sedan,: MODEL
  5d: MODEL
  prologue,: MODEL
unclassified:
- fhev
- navi
