make: mitsubishi
generated_at: '2026-06-23T11:35:35.109010'
schema_version: '1.0'
fuel_type_category: ENGINE_TYPE
token_map:
  '*ltd': PACKAGE
  avail*: PACKAGE
  awc: DRIVETRAIN
  black: PACKAGE
  carbon: PACKAGE
  cvt: TRANSMISSION
  edition: PACKAGE
  es: TRIM
  ex: TRIM
  ex-l: TRIM
  fwd: DRIVETRAIN
  gt: TRIM
  le: TRIM
  limited: TRIM
  manual: TRANSMISSION
  noir: TRIM
  phev: ENGINE_TYPE
  pkg: PACKAGE
  plus: TRIM
  premium: TRIM
  s-awc: DRIVETRAIN
  se: TRIM
  sel: TRIM
  ta: TRIM
  touring: TRIM
  w/tech: PACKAGE
  cross: MODEL
  eclipse: MODEL
  rvr: MODEL
  outlander: MODEL
  mirage: MODEL
  g4: MODEL
unclassified:
- ltd
