make: mitsubishi
generated_at: '2026-06-23T11:35:35.109010'
schema_version: '1.0'
fuel_type_category: ENGINE_TYPE

token_map:
  Outlander: MODEL
  RVR: MODEL
  Eclipse Cross: MODEL
  eclipse: MODEL
  cross: MODEL
  Mirage: MODEL
  Mirage G4: MODEL
  Lancer: MODEL
  Lancer Evolution: MODEL
  i-MiEV: MODEL
  Raider: MODEL
  Endeavor: MODEL
  Galant: MODEL


  gt: TRIM
  GT Premium: TRIM
  gt-premium: TRIM
  le: TRIM
  limited: TRIM
  noir: TRIM
  se: TRIM
  sel: TRIM
  es: TRIM
  s: TRIM
  premium: TRIM
  edition: TRIM
  Trail Edition: TRIM
  RALLIART: TRIM
  Black Edition: TRIM
  Launch Edition: TRIM
  Special Edition: TRIM
  Anniversary Edition: TRIM
  BE: TRIM

  fwd: DRIVETRAIN
  s-awc: DRIVETRAIN
  awc: DRIVETRAIN

  cvt: TRANSMISSION
  manual: TRANSMISSION

  phev: ENGINE_TYPE
  plug-in hybrid: ENGINE_TYPE
  mhev: ENGINE_TYPE
  hev: ENGINE_TYPE
  ev: ENGINE_TYPE

unclassified:

