make: HYUNDAI
generated_at: '2026-07-28T15:34:41.571209'
keyword_count: 52
keywords:
- '*ltd'
- +
- 1.6t
- 2.0l
- 2.5l
- 2.5t
- 7-passenger
- 8-passenger
- avail*
- awd
- calligraphy
- dct
- edition
- essential
- fwd
- green
- interior
- ivt
- long
- luxury
- manual
- n-line
- nhl
- night
- package
- preferred
- preferred-trend
- pro
- range
- roof
- rwd
- sedan
- special
- sport
- standard
- tcr
- trend
- two-tone
- ultimate
- urban
- w/beige
- w/black
- w/colour
- w/denim
- w/luxury
- w/n-line
- w/sage-green
- w/tech
- w/trend
- w/two-tone
- w/ultimate
- xrt
